/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author Hugo
 */
public class InterfazGrafica extends javax.swing.JFrame {

    /**
     * Creates new form Mockup
     */
    public InterfazGrafica() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        profesor0 = new javax.swing.JFrame();
        background1 = new javax.swing.JPanel();
        bannerP1 = new javax.swing.JLabel();
        botonPr0Atras = new javax.swing.JButton();
        administrador0 = new javax.swing.JFrame();
        background2 = new javax.swing.JPanel();
        bannerAd1 = new javax.swing.JLabel();
        botonAd0Atras = new javax.swing.JButton();
        alumno0 = new javax.swing.JFrame();
        background3 = new javax.swing.JPanel();
        bannerAl1 = new javax.swing.JLabel();
        botonAl0Atras = new javax.swing.JButton();
        adminCrearSala = new javax.swing.JFrame();
        background4 = new javax.swing.JPanel();
        bannerAdminCS = new javax.swing.JLabel();
        adminCrearProfesor = new javax.swing.JFrame();
        background5 = new javax.swing.JPanel();
        bannerAdminCP = new javax.swing.JLabel();
        adminCrearCurso = new javax.swing.JFrame();
        background6 = new javax.swing.JPanel();
        bannerAdminCCu = new javax.swing.JLabel();
        adminCrearCarrera = new javax.swing.JFrame();
        background7 = new javax.swing.JPanel();
        bannerAdminCCa = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        banner = new javax.swing.JLabel();
        ingComo = new javax.swing.JLabel();
        botonProfe = new javax.swing.JButton();
        botonAdmin = new javax.swing.JButton();
        botonAlumno = new javax.swing.JButton();
        logoUniversidad = new javax.swing.JLabel();

        profesor0.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        profesor0.setTitle("Profesor");
        profesor0.setLocation(new java.awt.Point(0, 0));
        profesor0.setPreferredSize(new java.awt.Dimension(720, 512));
        profesor0.setResizable(false);

        background1.setBackground(new java.awt.Color(236, 236, 236));

        bannerP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profe1.jpg"))); // NOI18N

        botonPr0Atras.setBackground(new java.awt.Color(236, 236, 236));
        botonPr0Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.jpg"))); // NOI18N
        botonPr0Atras.setToolTipText("");
        botonPr0Atras.setAlignmentY(0.0F);
        botonPr0Atras.setBorder(null);
        botonPr0Atras.setBorderPainted(false);
        botonPr0Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPr0AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bannerP1)
                    .addComponent(botonPr0Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addComponent(bannerP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(botonPr0Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout profesor0Layout = new javax.swing.GroupLayout(profesor0.getContentPane());
        profesor0.getContentPane().setLayout(profesor0Layout);
        profesor0Layout.setHorizontalGroup(
            profesor0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        profesor0Layout.setVerticalGroup(
            profesor0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        administrador0.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        administrador0.setPreferredSize(new java.awt.Dimension(720, 512));
        administrador0.setResizable(false);

        background2.setBackground(new java.awt.Color(236, 236, 236));

        bannerAd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin1.jpg"))); // NOI18N

        botonAd0Atras.setBackground(new java.awt.Color(236, 236, 236));
        botonAd0Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.jpg"))); // NOI18N
        botonAd0Atras.setToolTipText("");
        botonAd0Atras.setAlignmentY(0.0F);
        botonAd0Atras.setBorder(null);
        botonAd0Atras.setBorderPainted(false);
        botonAd0Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAd0AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bannerAd1)
                    .addComponent(botonAd0Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addComponent(bannerAd1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(botonAd0Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout administrador0Layout = new javax.swing.GroupLayout(administrador0.getContentPane());
        administrador0.getContentPane().setLayout(administrador0Layout);
        administrador0Layout.setHorizontalGroup(
            administrador0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        administrador0Layout.setVerticalGroup(
            administrador0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        alumno0.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        alumno0.setPreferredSize(new java.awt.Dimension(720, 512));
        alumno0.setResizable(false);

        background3.setBackground(new java.awt.Color(236, 236, 236));

        bannerAl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/alumno1.jpg"))); // NOI18N

        botonAl0Atras.setBackground(new java.awt.Color(236, 236, 236));
        botonAl0Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/atras.jpg"))); // NOI18N
        botonAl0Atras.setToolTipText("");
        botonAl0Atras.setAlignmentY(0.0F);
        botonAl0Atras.setBorder(null);
        botonAl0Atras.setBorderPainted(false);
        botonAl0Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAl0AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background3Layout = new javax.swing.GroupLayout(background3);
        background3.setLayout(background3Layout);
        background3Layout.setHorizontalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background3Layout.createSequentialGroup()
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bannerAl1)
                    .addComponent(botonAl0Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        background3Layout.setVerticalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background3Layout.createSequentialGroup()
                .addComponent(bannerAl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 340, Short.MAX_VALUE)
                .addComponent(botonAl0Atras, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout alumno0Layout = new javax.swing.GroupLayout(alumno0.getContentPane());
        alumno0.getContentPane().setLayout(alumno0Layout);
        alumno0Layout.setHorizontalGroup(
            alumno0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        alumno0Layout.setVerticalGroup(
            alumno0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        adminCrearSala.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        adminCrearSala.setTitle("Administrador: Crear Sala");
        adminCrearSala.setPreferredSize(new java.awt.Dimension(720, 512));
        adminCrearSala.setResizable(false);

        background4.setBackground(new java.awt.Color(236, 236, 236));

        bannerAdminCS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin-cs1.jpg"))); // NOI18N

        javax.swing.GroupLayout background4Layout = new javax.swing.GroupLayout(background4);
        background4.setLayout(background4Layout);
        background4Layout.setHorizontalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addComponent(bannerAdminCS)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        background4Layout.setVerticalGroup(
            background4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background4Layout.createSequentialGroup()
                .addComponent(bannerAdminCS)
                .addGap(0, 384, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminCrearSalaLayout = new javax.swing.GroupLayout(adminCrearSala.getContentPane());
        adminCrearSala.getContentPane().setLayout(adminCrearSalaLayout);
        adminCrearSalaLayout.setHorizontalGroup(
            adminCrearSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adminCrearSalaLayout.setVerticalGroup(
            adminCrearSalaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        adminCrearProfesor.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        adminCrearProfesor.setTitle("Administrador: Crear Profesor");
        adminCrearProfesor.setPreferredSize(new java.awt.Dimension(720, 512));
        adminCrearProfesor.setResizable(false);

        background5.setBackground(new java.awt.Color(236, 236, 236));

        bannerAdminCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin-ip1.jpg"))); // NOI18N

        javax.swing.GroupLayout background5Layout = new javax.swing.GroupLayout(background5);
        background5.setLayout(background5Layout);
        background5Layout.setHorizontalGroup(
            background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background5Layout.createSequentialGroup()
                .addComponent(bannerAdminCP)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        background5Layout.setVerticalGroup(
            background5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background5Layout.createSequentialGroup()
                .addComponent(bannerAdminCP)
                .addGap(0, 384, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminCrearProfesorLayout = new javax.swing.GroupLayout(adminCrearProfesor.getContentPane());
        adminCrearProfesor.getContentPane().setLayout(adminCrearProfesorLayout);
        adminCrearProfesorLayout.setHorizontalGroup(
            adminCrearProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adminCrearProfesorLayout.setVerticalGroup(
            adminCrearProfesorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        adminCrearCurso.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        adminCrearCurso.setTitle("Administrador: Crear Curso");
        adminCrearCurso.setPreferredSize(new java.awt.Dimension(720, 512));
        adminCrearCurso.setResizable(false);

        background6.setBackground(new java.awt.Color(236, 236, 236));

        bannerAdminCCu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin-cc1.jpg"))); // NOI18N

        javax.swing.GroupLayout background6Layout = new javax.swing.GroupLayout(background6);
        background6.setLayout(background6Layout);
        background6Layout.setHorizontalGroup(
            background6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background6Layout.createSequentialGroup()
                .addComponent(bannerAdminCCu)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        background6Layout.setVerticalGroup(
            background6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background6Layout.createSequentialGroup()
                .addComponent(bannerAdminCCu)
                .addGap(0, 384, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminCrearCursoLayout = new javax.swing.GroupLayout(adminCrearCurso.getContentPane());
        adminCrearCurso.getContentPane().setLayout(adminCrearCursoLayout);
        adminCrearCursoLayout.setHorizontalGroup(
            adminCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adminCrearCursoLayout.setVerticalGroup(
            adminCrearCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        adminCrearCarrera.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        adminCrearCarrera.setTitle("Administrador: Crear Carrera");
        adminCrearCarrera.setPreferredSize(new java.awt.Dimension(720, 512));
        adminCrearCarrera.setResizable(false);

        background7.setBackground(new java.awt.Color(236, 236, 236));

        bannerAdminCCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin-cca1.jpg"))); // NOI18N

        javax.swing.GroupLayout background7Layout = new javax.swing.GroupLayout(background7);
        background7.setLayout(background7Layout);
        background7Layout.setHorizontalGroup(
            background7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background7Layout.createSequentialGroup()
                .addComponent(bannerAdminCCa)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        background7Layout.setVerticalGroup(
            background7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background7Layout.createSequentialGroup()
                .addComponent(bannerAdminCCa)
                .addGap(0, 384, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout adminCrearCarreraLayout = new javax.swing.GroupLayout(adminCrearCarrera.getContentPane());
        adminCrearCarrera.getContentPane().setLayout(adminCrearCarreraLayout);
        adminCrearCarreraLayout.setHorizontalGroup(
            adminCrearCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        adminCrearCarreraLayout.setVerticalGroup(
            adminCrearCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Inicial");
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        background.setBackground(new java.awt.Color(236, 236, 236));
        background.setPreferredSize(new java.awt.Dimension(720, 512));

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/menu.jpg"))); // NOI18N

        ingComo.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        ingComo.setForeground(new java.awt.Color(51, 51, 51));
        ingComo.setText("Ingresar como:");

        botonProfe.setBackground(new java.awt.Color(208, 22, 22));
        botonProfe.setFont(new java.awt.Font("Eras Medium ITC", 0, 22)); // NOI18N
        botonProfe.setText("Profesor");
        botonProfe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProfeActionPerformed(evt);
            }
        });

        botonAdmin.setBackground(new java.awt.Color(208, 22, 22));
        botonAdmin.setFont(new java.awt.Font("Eras Medium ITC", 0, 22)); // NOI18N
        botonAdmin.setText("Administrador");
        botonAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAdminActionPerformed(evt);
            }
        });

        botonAlumno.setBackground(new java.awt.Color(208, 22, 22));
        botonAlumno.setFont(new java.awt.Font("Eras Medium ITC", 0, 22)); // NOI18N
        botonAlumno.setText("Alumno");
        botonAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlumnoActionPerformed(evt);
            }
        });

        logoUniversidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logouni.jpg"))); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingComo)
                    .addGroup(backgroundLayout.createSequentialGroup()
                        .addComponent(botonProfe, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(botonAdmin)
                        .addGap(74, 74, 74)
                        .addComponent(botonAlumno)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(banner)
                    .addComponent(logoUniversidad))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addComponent(banner)
                .addGap(59, 59, 59)
                .addComponent(ingComo)
                .addGap(36, 36, 36)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonProfe, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(logoUniversidad))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonProfeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProfeActionPerformed
        this.profesor0.pack();
        this.profesor0.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonProfeActionPerformed

    private void botonAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAdminActionPerformed
        this.administrador0.pack();
        this.administrador0.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonAdminActionPerformed

    private void botonAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlumnoActionPerformed
        this.alumno0.pack();
        this.alumno0.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botonAlumnoActionPerformed

    private void botonPr0AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPr0AtrasActionPerformed
        this.profesor0.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_botonPr0AtrasActionPerformed

    private void botonAd0AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAd0AtrasActionPerformed
        this.administrador0.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_botonAd0AtrasActionPerformed

    private void botonAl0AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAl0AtrasActionPerformed
        this.alumno0.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_botonAl0AtrasActionPerformed
  
    
    
    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame adminCrearCarrera;
    private javax.swing.JFrame adminCrearCurso;
    private javax.swing.JFrame adminCrearProfesor;
    private javax.swing.JFrame adminCrearSala;
    private javax.swing.JFrame administrador0;
    private javax.swing.JFrame alumno0;
    private javax.swing.JPanel background;
    private javax.swing.JPanel background1;
    private javax.swing.JPanel background2;
    private javax.swing.JPanel background3;
    private javax.swing.JPanel background4;
    private javax.swing.JPanel background5;
    private javax.swing.JPanel background6;
    private javax.swing.JPanel background7;
    private javax.swing.JLabel banner;
    private javax.swing.JLabel bannerAd1;
    private javax.swing.JLabel bannerAdminCCa;
    private javax.swing.JLabel bannerAdminCCu;
    private javax.swing.JLabel bannerAdminCP;
    private javax.swing.JLabel bannerAdminCS;
    private javax.swing.JLabel bannerAl1;
    private javax.swing.JLabel bannerP1;
    private javax.swing.JButton botonAd0Atras;
    private javax.swing.JButton botonAdmin;
    private javax.swing.JButton botonAl0Atras;
    private javax.swing.JButton botonAlumno;
    private javax.swing.JButton botonPr0Atras;
    private javax.swing.JButton botonProfe;
    private javax.swing.JLabel ingComo;
    private javax.swing.JLabel logoUniversidad;
    private javax.swing.JFrame profesor0;
    // End of variables declaration//GEN-END:variables
}
