/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;

/**
 *
 * @author Luciano García
 */
public class InterfazGrafica extends javax.swing.JFrame {
    
    Gestion g = new Gestion();

    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsNivel0 = new javax.swing.JTabbedPane();
        tabsAdminNivel1 = new javax.swing.JTabbedPane();
        background0 = new javax.swing.JPanel();
        bannerAdminCCu = new javax.swing.JLabel();
        scrollNombreCurso = new javax.swing.JScrollPane();
        valorNombreCurso1 = new javax.swing.JTextPane();
        nombreCurso1 = new javax.swing.JLabel();
        botonAceptarCurso = new javax.swing.JButton();
        background1 = new javax.swing.JPanel();
        bannerAdminIP = new javax.swing.JLabel();
        nombreProfesor = new javax.swing.JLabel();
        scrollProfesor2 = new javax.swing.JScrollPane();
        valorCorreoInstitucional = new javax.swing.JTextPane();
        correoPersonal = new javax.swing.JLabel();
        correoInstitucional = new javax.swing.JLabel();
        scrollProfesor1 = new javax.swing.JScrollPane();
        valorNombreProfesor2 = new javax.swing.JTextPane();
        scrollProfesor3 = new javax.swing.JScrollPane();
        valorCorreoPersonal = new javax.swing.JTextPane();
        contacto = new javax.swing.JLabel();
        scrollProfesor4 = new javax.swing.JScrollPane();
        valorContacto = new javax.swing.JTextPane();
        botonAceptarProfesor = new javax.swing.JButton();
        background2 = new javax.swing.JPanel();
        bannerAdminCCa = new javax.swing.JLabel();
        nombreCarrera = new javax.swing.JLabel();
        scrollNombreCa = new javax.swing.JScrollPane();
        valorNombreCa = new javax.swing.JTextPane();
        botonAceptarCarrera = new javax.swing.JButton();
        background3 = new javax.swing.JPanel();
        bannerAdminCS = new javax.swing.JLabel();
        nombreSala = new javax.swing.JLabel();
        scrollNombreSala = new javax.swing.JScrollPane();
        valorNombreSala = new javax.swing.JTextPane();
        botonAceptar = new javax.swing.JButton();
        tabsProfeNivel1 = new javax.swing.JTabbedPane();
        tabsAlumnoNivel1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(59, 59, 59));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setResizable(false);

        tabsNivel0.setBackground(new java.awt.Color(59, 59, 59));
        tabsNivel0.setForeground(new java.awt.Color(204, 204, 204));
        tabsNivel0.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabsNivel0.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabsNivel0.setDoubleBuffered(true);
        tabsNivel0.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        tabsNivel0.setMinimumSize(new java.awt.Dimension(0, 0));
        tabsNivel0.setPreferredSize(new java.awt.Dimension(1920, 1080));

        tabsAdminNivel1.setBackground(new java.awt.Color(59, 59, 59));
        tabsAdminNivel1.setForeground(new java.awt.Color(204, 204, 204));
        tabsAdminNivel1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabsAdminNivel1.setFont(new java.awt.Font("Eras Medium ITC", 0, 18)); // NOI18N
        tabsAdminNivel1.setMinimumSize(new java.awt.Dimension(0, 0));
        tabsAdminNivel1.setPreferredSize(new java.awt.Dimension(1910, 1036));

        background0.setBackground(new java.awt.Color(216, 216, 216));
        background0.setPreferredSize(new java.awt.Dimension(1910, 1007));

        bannerAdminCCu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannerAdminCrearCurso.jpg"))); // NOI18N
        bannerAdminCCu.setText("jLabel4");
        bannerAdminCCu.setIconTextGap(0);
        bannerAdminCCu.setPreferredSize(new java.awt.Dimension(1910, 103));

        scrollNombreCurso.setViewportView(valorNombreCurso1);

        nombreCurso1.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        nombreCurso1.setForeground(new java.awt.Color(51, 51, 51));
        nombreCurso1.setText("Nombre curso");
        nombreCurso1.setMaximumSize(new java.awt.Dimension(135, 28));
        nombreCurso1.setMinimumSize(new java.awt.Dimension(135, 28));
        nombreCurso1.setPreferredSize(new java.awt.Dimension(135, 28));

        botonAceptarCurso.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        botonAceptarCurso.setText("Aceptar");
        botonAceptarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background0Layout = new javax.swing.GroupLayout(background0);
        background0.setLayout(background0Layout);
        background0Layout.setHorizontalGroup(
            background0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background0Layout.createSequentialGroup()
                .addComponent(bannerAdminCCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(background0Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(nombreCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background0Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        background0Layout.setVerticalGroup(
            background0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background0Layout.createSequentialGroup()
                .addComponent(bannerAdminCCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addGroup(background0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollNombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCurso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 688, Short.MAX_VALUE)
                .addComponent(botonAceptarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        tabsAdminNivel1.addTab("Crear curso", background0);

        background1.setBackground(new java.awt.Color(216, 216, 216));

        bannerAdminIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannerAdminCrearProfesor.jpg"))); // NOI18N

        nombreProfesor.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        nombreProfesor.setForeground(new java.awt.Color(51, 51, 51));
        nombreProfesor.setText("Nombre profesor");
        nombreProfesor.setMaximumSize(new java.awt.Dimension(135, 28));
        nombreProfesor.setMinimumSize(new java.awt.Dimension(135, 28));
        nombreProfesor.setPreferredSize(new java.awt.Dimension(135, 28));

        scrollProfesor2.setViewportView(valorCorreoInstitucional);

        correoPersonal.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        correoPersonal.setForeground(new java.awt.Color(51, 51, 51));
        correoPersonal.setText("Correo personal");
        correoPersonal.setMaximumSize(new java.awt.Dimension(135, 28));
        correoPersonal.setMinimumSize(new java.awt.Dimension(135, 28));
        correoPersonal.setPreferredSize(new java.awt.Dimension(135, 28));

        correoInstitucional.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        correoInstitucional.setForeground(new java.awt.Color(51, 51, 51));
        correoInstitucional.setText("Correo institucional");
        correoInstitucional.setMaximumSize(new java.awt.Dimension(135, 28));
        correoInstitucional.setMinimumSize(new java.awt.Dimension(135, 28));
        correoInstitucional.setPreferredSize(new java.awt.Dimension(135, 28));

        scrollProfesor1.setViewportView(valorNombreProfesor2);

        scrollProfesor3.setViewportView(valorCorreoPersonal);

        contacto.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        contacto.setForeground(new java.awt.Color(51, 51, 51));
        contacto.setText("Contacto");
        contacto.setMaximumSize(new java.awt.Dimension(135, 28));
        contacto.setMinimumSize(new java.awt.Dimension(135, 28));
        contacto.setPreferredSize(new java.awt.Dimension(135, 28));

        scrollProfesor4.setViewportView(valorContacto);

        botonAceptarProfesor.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        botonAceptarProfesor.setText("Aceptar");
        botonAceptarProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarProfesorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addComponent(bannerAdminIP)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correoInstitucional, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(correoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(contacto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollProfesor3, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollProfesor2, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollProfesor1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollProfesor4, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addComponent(bannerAdminIP)
                .addGap(91, 91, 91)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nombreProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollProfesor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(correoInstitucional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollProfesor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(correoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollProfesor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollProfesor4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 557, Short.MAX_VALUE)
                .addComponent(botonAceptarProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        tabsAdminNivel1.addTab("Crear profesor", background1);

        background2.setBackground(new java.awt.Color(216, 216, 216));

        bannerAdminCCa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannerAdminCrearCarrera.jpg"))); // NOI18N
        bannerAdminCCa.setToolTipText("");

        nombreCarrera.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        nombreCarrera.setForeground(new java.awt.Color(51, 51, 51));
        nombreCarrera.setText("Nombre carrera");
        nombreCarrera.setMaximumSize(new java.awt.Dimension(135, 28));
        nombreCarrera.setMinimumSize(new java.awt.Dimension(135, 28));
        nombreCarrera.setPreferredSize(new java.awt.Dimension(135, 28));

        scrollNombreCa.setViewportView(valorNombreCa);

        botonAceptarCarrera.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        botonAceptarCarrera.setText("Aceptar");
        botonAceptarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarCarreraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background2Layout = new javax.swing.GroupLayout(background2);
        background2.setLayout(background2Layout);
        background2Layout.setHorizontalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(nombreCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(scrollNombreCa, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(background2Layout.createSequentialGroup()
                .addComponent(bannerAdminCCa)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        background2Layout.setVerticalGroup(
            background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background2Layout.createSequentialGroup()
                .addComponent(bannerAdminCCa)
                .addGap(104, 104, 104)
                .addGroup(background2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollNombreCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 681, Short.MAX_VALUE)
                .addComponent(botonAceptarCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        tabsAdminNivel1.addTab("Crear carrera", background2);

        background3.setBackground(new java.awt.Color(216, 216, 216));

        bannerAdminCS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bannerAdminCrearSala.jpg"))); // NOI18N

        nombreSala.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        nombreSala.setForeground(new java.awt.Color(51, 51, 51));
        nombreSala.setText("Nombre sala");

        scrollNombreSala.setViewportView(valorNombreSala);

        botonAceptar.setFont(new java.awt.Font("Eras Medium ITC", 0, 24)); // NOI18N
        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background3Layout = new javax.swing.GroupLayout(background3);
        background3.setLayout(background3Layout);
        background3Layout.setHorizontalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background3Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(nombreSala)
                .addGap(29, 29, 29)
                .addComponent(scrollNombreSala, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(background3Layout.createSequentialGroup()
                .addComponent(bannerAdminCS)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        background3Layout.setVerticalGroup(
            background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, background3Layout.createSequentialGroup()
                .addComponent(bannerAdminCS)
                .addGap(103, 103, 103)
                .addGroup(background3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollNombreSala)
                    .addComponent(nombreSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 684, Short.MAX_VALUE)
                .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        tabsAdminNivel1.addTab("Crear sala", background3);

        tabsNivel0.addTab("Administrador", tabsAdminNivel1);
        tabsAdminNivel1.getAccessibleContext().setAccessibleName("Crear Sala");
        tabsAdminNivel1.getAccessibleContext().setAccessibleDescription("");

        tabsProfeNivel1.setBackground(new java.awt.Color(59, 59, 59));
        tabsProfeNivel1.setMinimumSize(new java.awt.Dimension(0, 0));
        tabsNivel0.addTab("Profesor", tabsProfeNivel1);

        tabsAlumnoNivel1.setMinimumSize(new java.awt.Dimension(0, 0));
        tabsNivel0.addTab("Alumno", tabsAlumnoNivel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsNivel0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsNivel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
        String a = this.valorNombreSala.getText();
        if (a.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese un nombre válido para la sala");
        }
        else {
            Sala s = new Sala(a);
            g.addSala(s);
            JOptionPane.showMessageDialog(rootPane, "Sala creada con éxito");   
        }
    }//GEN-LAST:event_botonAceptarActionPerformed

    private void botonAceptarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarCarreraActionPerformed
        String a = this.valorNombreCa.getText();
        if (a.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese un nombre válido para la carrera");
        }
        else {
            g.addCarrera(a);
            JOptionPane.showMessageDialog(rootPane, "Carrera creada con éxito");   
        }
    }//GEN-LAST:event_botonAceptarCarreraActionPerformed

    private void botonAceptarProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarProfesorActionPerformed
        String a = this.valorNombreProfesor2.getText();
        String b = this.valorCorreoInstitucional.getText();
        String c = this.valorCorreoPersonal.getText();
        String d = this.valorContacto.getText();
        if (a.equals("") || b.equals("") || c.equals("") || d.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Faltan datos por ingresar. Asegurese de completar todas las casillas");
        }
        else {
            Profesor p = new Profesor(a, c, d, b);
            g.addProfesor(p);
            JOptionPane.showMessageDialog(rootPane, "Profesor creado y añadido con éxito");   
        }
    }//GEN-LAST:event_botonAceptarProfesorActionPerformed

    private void botonAceptarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarCursoActionPerformed
        String a = this.valorNombreCurso1.getText();
        if (a.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese un nombre válido para el curso");
        }
        else {
            Curso c = new Curso(a);
            g.addCurso(c);
            JOptionPane.showMessageDialog(rootPane, "Curso creado con éxito");   
        }
    }//GEN-LAST:event_botonAceptarCursoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(InterfazGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new InterfazGrafica().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background0;
    private javax.swing.JPanel background1;
    private javax.swing.JPanel background2;
    private javax.swing.JPanel background3;
    private javax.swing.JLabel bannerAdminCCa;
    private javax.swing.JLabel bannerAdminCCu;
    private javax.swing.JLabel bannerAdminCS;
    private javax.swing.JLabel bannerAdminIP;
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonAceptarCarrera;
    private javax.swing.JButton botonAceptarCurso;
    private javax.swing.JButton botonAceptarProfesor;
    private javax.swing.JLabel contacto;
    private javax.swing.JLabel correoInstitucional;
    private javax.swing.JLabel correoPersonal;
    private javax.swing.JLabel nombreCarrera;
    private javax.swing.JLabel nombreCurso1;
    private javax.swing.JLabel nombreProfesor;
    private javax.swing.JLabel nombreSala;
    private javax.swing.JScrollPane scrollNombreCa;
    private javax.swing.JScrollPane scrollNombreCurso;
    private javax.swing.JScrollPane scrollNombreSala;
    private javax.swing.JScrollPane scrollProfesor1;
    private javax.swing.JScrollPane scrollProfesor2;
    private javax.swing.JScrollPane scrollProfesor3;
    private javax.swing.JScrollPane scrollProfesor4;
    private javax.swing.JTabbedPane tabsAdminNivel1;
    private javax.swing.JTabbedPane tabsAlumnoNivel1;
    private javax.swing.JTabbedPane tabsNivel0;
    private javax.swing.JTabbedPane tabsProfeNivel1;
    private javax.swing.JTextPane valorContacto;
    private javax.swing.JTextPane valorCorreoInstitucional;
    private javax.swing.JTextPane valorCorreoPersonal;
    private javax.swing.JTextPane valorNombreCa;
    private javax.swing.JTextPane valorNombreCurso1;
    private javax.swing.JTextPane valorNombreProfesor2;
    private javax.swing.JTextPane valorNombreSala;
    // End of variables declaration//GEN-END:variables
}
